[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; style-src 'self' https://fonts.googleapis.com; script-src 'self' 'sha256-s+6eAev9gNYguvqpBr4EK0JcGBbqCloZsapxmRCKBoc='; img-src 'self' https://digi-api.com https://www.transparenttextures.com; connect-src 'self' https://digi-api.com"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"