[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://digimon-api.com/api/v1/:splat"
  status = 200
  force = true
  headers = { "Access-Control-Allow-Origin" = "*" }